# Generated by Django 4.0.3 on 2022-03-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='to_agent',
            new_name='top_agent',
        ),
    ]
