# Generated by Django 4.0.3 on 2022-03-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='property',
            managers=[
            ],
        ),
    ]
